FROM python:3.14.0-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock README.md ./

RUN uv sync --locked --no-install-project

COPY /src/max_hackaton ./src/max_hackaton

WORKDIR /src/max_hackaton

CMD ["uv", "run", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
