/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить онбординг */
        post: operations["complete_onboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/personal-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Личные данные */
        get: operations["get_personal_data"];
        /** Сохранить личные данные */
        put: operations["update_personal_data"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ближайшие разрешённые даты донации */
        get: operations["get_eligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Уровень донора и путь к званию */
        get: operations["get_progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/donations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История донаций */
        get: operations["get_donations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Рефералы */
        get: operations["get_referrals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все субъекты РФ по алфавиту */
        get: operations["list_regions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Регион по координатам */
        get: operations["locate_region"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карта-светофор по регионам */
        get: operations["get_map_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/booking/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Календарь доступности на 2 месяца */
        get: operations["get_booking_dates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/booking/centers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Центры со свободными слотами на дату */
        get: operations["get_booking_centers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/booking/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Слоты центра на дату */
        get: operations["get_booking_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активная запись */
        get: operations["get_current_appointment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Записаться */
        post: operations["create_appointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{appointment_id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Перенести запись */
        post: operations["reschedule_appointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{appointment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить запись */
        post: operations["cancel_appointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сбросить демо-профиль */
        post: operations["demo_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/appointments/{appointment_id}/remind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить напоминание сразу */
        post: operations["demo_remind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/appointments/{appointment_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Засчитать донацию */
        post: operations["demo_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Appointment */
        Appointment: {
            /** Id */
            id: number;
            donation_type: components["schemas"]["DonationType"];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Local Time
             * @example 09:30
             */
            local_time: string;
            center: components["schemas"]["AppointmentCenter"];
        };
        /** AppointmentCenter */
        AppointmentCenter: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Region Id */
            region_id: number;
        };
        /** AppointmentResponse */
        AppointmentResponse: {
            appointment: components["schemas"]["Appointment"] | null;
        };
        /**
         * BloodGroup
         * @description Группа крови и резус
         * @enum {string}
         */
        BloodGroup: "1+" | "1-" | "2+" | "2-" | "3+" | "3-" | "4+" | "4-";
        /** BloodInfo */
        BloodInfo: {
            group: components["schemas"]["BloodGroup"] | null;
            /** Kell */
            kell: ("K+" | "K-") | null;
            /**
             * Phenotype
             * @example CcDee
             */
            phenotype: string | null;
            /**
             * Donor Code
             * @example 1234-5678
             */
            donor_code: string | null;
        };
        /** BookingCenter */
        BookingCenter: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Photo Url */
            photo_url: string | null;
            /** Free Slots */
            free_slots: number;
            /** Distance Km */
            distance_km: number | null;
            group_status: components["schemas"]["StockStatus"] | null;
        };
        /** BookingDates */
        BookingDates: {
            /**
             * From
             * Format: date
             */
            from: string;
            /**
             * To
             * Format: date
             */
            to: string;
            /**
             * Earliest Allowed
             * Format: date
             */
            earliest_allowed: string;
            /** First Available */
            first_available: string | null;
            /** Days */
            days: components["schemas"]["BookingDay"][];
        };
        /** BookingDay */
        BookingDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Available */
            available: boolean;
        };
        /** BookingSlots */
        BookingSlots: {
            center: components["schemas"]["SlotsCenter"];
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Groups */
            groups: components["schemas"]["SlotGroup"][];
        };
        /** Donation */
        Donation: {
            /** Id */
            id: number;
            donation_type: components["schemas"]["DonationType"];
            /**
             * Donated On
             * Format: date
             */
            donated_on: string;
            /** Center Name */
            center_name: string | null;
        };
        /** DonationHistory */
        DonationHistory: {
            /** Total */
            total: number;
            /** Years */
            years: components["schemas"]["DonationYear"][];
        };
        /**
         * DonationType
         * @description Вид донации: цельная кровь или плазма.
         * @enum {string}
         */
        DonationType: "whole_blood" | "plasma";
        /** DonationYear */
        DonationYear: {
            /** Year */
            year: number;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["Donation"][];
        };
        /** Eligibility */
        Eligibility: {
            next_allowed: components["schemas"]["NextAllowed"];
            interval_active: components["schemas"]["IntervalActive"];
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Fields */
            fields: {
                [key: string]: string;
            } | null;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "unauthorized" | "not_found" | "validation_error" | "slot_not_found" | "slot_taken" | "active_exists" | "interval_not_passed" | "personal_data_incomplete" | "appointment_not_found" | "appointment_not_active" | "demo_disabled" | "internal_error";
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Honorary */
        Honorary: {
            whole: components["schemas"]["HonoraryCounter"];
            plasma: components["schemas"]["HonoraryCounter"];
            mixed: components["schemas"]["HonoraryMixed"];
            /** Achieved */
            achieved: boolean;
            eta: components["schemas"]["HonoraryEta"] | null;
        };
        /** HonoraryCounter */
        HonoraryCounter: {
            /** Count */
            count: number;
            /** Goal */
            goal: number;
        };
        /** HonoraryEta */
        HonoraryEta: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Years */
            years: number;
            /** Months */
            months: number;
        };
        /** HonoraryMixed */
        HonoraryMixed: {
            /** Count */
            count: number;
            /**
             * Goal
             * @enum {integer}
             */
            goal: 40 | 60;
            /** Whole Needed For 40 */
            whole_needed_for_40: number;
        };
        /** IntervalActive */
        IntervalActive: {
            /** Whole Blood */
            whole_blood: boolean;
            /** Plasma */
            plasma: boolean;
        };
        /** Level */
        Level: {
            code: components["schemas"]["LevelCode"];
            /** Name */
            name: string;
            /** Threshold */
            threshold: number;
            next: components["schemas"]["NextLevel"] | null;
            /** Is Max */
            is_max: boolean;
        };
        /**
         * LevelCode
         * @enum {string}
         */
        LevelCode: "future_donor" | "novice" | "active" | "experienced" | "mentor" | "legend";
        /** LocateRegionResponse */
        LocateRegionResponse: {
            region: components["schemas"]["Region"] | null;
        };
        /** MapRegion */
        MapRegion: {
            /** Code */
            code: string;
            /** Statuses */
            statuses: {
                [key: string]: components["schemas"]["StockStatus"];
            };
            worst: components["schemas"]["StockStatus"] | null;
        };
        /** MapStatus */
        MapStatus: {
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Regions */
            regions: components["schemas"]["MapRegion"][];
        };
        /** Me */
        Me: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string | null;
            /** Photo Url */
            photo_url: string | null;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            blood: components["schemas"]["BloodInfo"];
            /** Referrals Count */
            referrals_count: number;
        };
        /** NextAllowed */
        NextAllowed: {
            /**
             * Whole Blood
             * Format: date
             */
            whole_blood: string;
            /**
             * Plasma
             * Format: date
             */
            plasma: string;
        };
        /** NextLevel */
        NextLevel: {
            code: components["schemas"]["LevelCode"];
            /** Name */
            name: string;
            /** Threshold */
            threshold: number;
            /** Remaining */
            remaining: number;
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /**
             * Consent
             * @constant
             */
            consent: true;
        };
        /** PersonalData */
        PersonalData: {
            /** Last Name */
            last_name: string | null;
            /** First Name */
            first_name: string | null;
            /** Middle Name */
            middle_name: string | null;
            /** Passport Series */
            passport_series: string | null;
            /** Passport Number */
            passport_number: string | null;
            /** Passport Issued By */
            passport_issued_by: string | null;
            /** Passport Division Code */
            passport_division_code: string | null;
            /** Oms Number */
            oms_number: string | null;
            /** Phone */
            phone: string | null;
            /** Email */
            email: string | null;
            /** Is Demo */
            is_demo: boolean;
            /** Missing Fields */
            missing_fields: components["schemas"]["PersonalDataField"][];
        };
        /**
         * PersonalDataField
         * @enum {string}
         */
        PersonalDataField: "last_name" | "first_name" | "middle_name" | "passport_series" | "passport_number" | "passport_issued_by" | "passport_division_code" | "oms_number" | "phone" | "email";
        /** PersonalDataInput */
        PersonalDataInput: {
            /** Last Name */
            last_name: string;
            /** First Name */
            first_name: string;
            /** Middle Name */
            middle_name?: string | null;
            /**
             * Passport Series
             * @example 4510
             */
            passport_series: string;
            /**
             * Passport Number
             * @example 123456
             */
            passport_number: string;
            /** Passport Issued By */
            passport_issued_by: string;
            /**
             * Passport Division Code
             * @example 770-001
             */
            passport_division_code: string;
            /**
             * Oms Number
             * @example 1234567890123456
             */
            oms_number: string;
            /**
             * Phone
             * @example +79001234567
             */
            phone: string;
            /**
             * Email
             * @example ivanov@mail.ru
             */
            email: string;
        };
        /** Progress */
        Progress: {
            /** Total */
            total: number;
            level: components["schemas"]["Level"];
            honorary: components["schemas"]["Honorary"];
        };
        /** Referrals */
        Referrals: {
            /** Count */
            count: number;
            /** Link */
            link: string;
        };
        /** Region */
        Region: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Has Centers */
            has_centers: boolean;
        };
        /** Slot */
        Slot: {
            /** Id */
            id: number;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Local Time
             * @example 09:30
             */
            local_time: string;
            /** Is Free */
            is_free: boolean;
        };
        /** SlotGroup */
        SlotGroup: {
            period: components["schemas"]["SlotPeriod"];
            /** Slots */
            slots: components["schemas"]["Slot"][];
        };
        /**
         * SlotPeriod
         * @enum {string}
         */
        SlotPeriod: "morning" | "day" | "evening";
        /** SlotRequest */
        SlotRequest: {
            /** Slot Id */
            slot_id: number;
        };
        /** SlotsCenter */
        SlotsCenter: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
        };
        /**
         * StockStatus
         * @description Запас крови группы: нет строки в таблице — «нет данных».
         * @enum {string}
         */
        StockStatus: "urgent" | "low" | "enough";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_onboarding: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_personal_data: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalData"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_personal_data: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalDataInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalData"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_eligibility: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eligibility"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_donations: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonationHistory"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_referrals: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Referrals"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regions: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locate_region: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocateRegionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_map_status: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_dates: {
        parameters: {
            query: {
                region_id: number;
                donation_type: components["schemas"]["DonationType"];
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDates"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_booking_centers: {
        parameters: {
            query: {
                region_id: number;
                donation_type: components["schemas"]["DonationType"];
                date: string;
                lat?: number | null;
                lon?: number | null;
                pin_center_id?: number | null;
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingCenter"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_booking_slots: {
        parameters: {
            query: {
                center_id: number;
                donation_type: components["schemas"]["DonationType"];
                date: string;
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingSlots"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_current_appointment: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_appointment: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reschedule_appointment: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_appointment: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_reset: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_remind: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_complete: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
