/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить онбординг */
        post: operations["complete_onboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/personal-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Личные данные */
        get: operations["get_personal_data"];
        /** Сохранить личные данные */
        put: operations["update_personal_data"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ближайшие разрешённые даты донации */
        get: operations["get_eligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Уровень донора и путь к званию */
        get: operations["get_progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/donations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История донаций */
        get: operations["get_donations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Рефералы */
        get: operations["get_referrals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/region": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Регион донора (для пушей о дефиците крови) */
        put: operations["update_region"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Вклад: литры и сколько людям могли помочь */
        get: operations["get_impact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/share-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка «Я сдал кровь» / «Мой уровень» для shareMaxContent */
        get: operations["get_share_card"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/after-donation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Последняя донация за год: документы и статус дня отдыха */
        get: operations["get_after_donation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/donations/{donation_id}/after": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Документы и день отдыха по конкретной донации */
        get: operations["get_donation_after"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/donations/{donation_id}/rest-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Отметить, использован ли доп. день отдыха */
        put: operations["update_rest_day"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/donations/{donation_id}/leave-application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Скачать заявление на доп. день отдыха (PDF или DOCX) */
        post: operations["download_leave_application"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/donations/{donation_id}/leave-application/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Прислать заявление файлом в чат с ботом */
        post: operations["send_leave_application"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все субъекты РФ по алфавиту */
        get: operations["list_regions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Регион по координатам */
        get: operations["locate_region"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карта-светофор по регионам */
        get: operations["get_map_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/centers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все центры крови для карты-светофора */
        get: operations["get_map_centers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/booking/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Календарь доступности на 2 месяца */
        get: operations["get_booking_dates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/booking/centers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Центры со свободными слотами на дату */
        get: operations["get_booking_centers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/booking/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Слоты центра на дату */
        get: operations["get_booking_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активная запись */
        get: operations["get_current_appointment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Записаться */
        post: operations["create_appointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{appointment_id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Перенести запись */
        post: operations["reschedule_appointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{appointment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить запись */
        post: operations["cancel_appointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать групповую донацию */
        post: operations["create_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои групповые донации: предстоящие или прошедшие */
        get: operations["my_groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Группа по коду из ссылки grp_<code> */
        get: operations["get_group"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{code}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Присоединиться к группе */
        post: operations["join_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сбросить демо-профиль */
        post: operations["demo_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/appointments/{appointment_id}/remind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить напоминание сразу */
        post: operations["demo_remind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/appointments/{appointment_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Засчитать донацию */
        post: operations["demo_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/appointments/{appointment_id}/ask-donated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Спросить «Сдали кровь?» сразу */
        post: operations["demo_ask_donated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/pushes/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Прислать проактивный пуш сейчас (без проверки условий) */
        post: operations["demo_push"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/pushes-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Прогнать ежедневную рассылку пушей сейчас */
        post: operations["demo_run_daily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AfterDonation
         * @description Что делать после донации: документы и доп. день отдыха (ст. 186 ТК РФ).
         */
        AfterDonation: {
            /** Donation Id */
            donation_id: number;
            donation_type: components["schemas"]["DonationType"];
            /**
             * Donated On
             * Format: date
             */
            donated_on: string;
            /** Center Name */
            center_name: string | null;
            /**
             * Documents
             * @description Что взять в центре крови
             */
            documents: string[];
            rest_day: components["schemas"]["RestDay"];
        };
        /** AfterDonationResponse */
        AfterDonationResponse: {
            after_donation: components["schemas"]["AfterDonation"] | null;
        };
        /** Appointment */
        Appointment: {
            /** Id */
            id: number;
            donation_type: components["schemas"]["DonationType"];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Local Time
             * @example 09:30
             */
            local_time: string;
            center: components["schemas"]["AppointmentCenter"];
        };
        /** AppointmentCenter */
        AppointmentCenter: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Region Id */
            region_id: number;
        };
        /** AppointmentResponse */
        AppointmentResponse: {
            appointment: components["schemas"]["Appointment"] | null;
        };
        /**
         * BloodGroup
         * @description Группа крови и резус
         * @enum {string}
         */
        BloodGroup: "1+" | "1-" | "2+" | "2-" | "3+" | "3-" | "4+" | "4-";
        /** BloodInfo */
        BloodInfo: {
            group: components["schemas"]["BloodGroup"] | null;
            /** Kell */
            kell: ("K+" | "K-") | null;
            /** Phenotype */
            phenotype: string | null;
            /** Donor Code */
            donor_code: string | null;
        };
        /** BookingCenter */
        BookingCenter: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Photo Url */
            photo_url: string | null;
            /** Free Slots */
            free_slots: number;
            /** Distance Km */
            distance_km: number | null;
            group_status: components["schemas"]["StockStatus"] | null;
            /**
             * Is Usual
             * @default false
             */
            is_usual: boolean;
        };
        /** BookingDates */
        BookingDates: {
            /**
             * From
             * Format: date
             */
            from: string;
            /**
             * To
             * Format: date
             */
            to: string;
            /**
             * Earliest Allowed
             * Format: date
             */
            earliest_allowed: string;
            /** First Available */
            first_available: string | null;
            /** Days */
            days: components["schemas"]["BookingDay"][];
        };
        /** BookingDay */
        BookingDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Available */
            available: boolean;
        };
        /** BookingSlots */
        BookingSlots: {
            center: components["schemas"]["SlotsCenter"];
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Groups */
            groups: components["schemas"]["SlotGroup"][];
        };
        /** DailyRunResult */
        DailyRunResult: {
            /** Sent */
            sent: number;
        };
        /**
         * DemoPushKind
         * @enum {string}
         */
        DemoPushKind: "interval_open" | "deficit" | "rest_day";
        /**
         * DocFormat
         * @enum {string}
         */
        DocFormat: "pdf" | "docx";
        /** Donation */
        Donation: {
            /** Id */
            id: number;
            donation_type: components["schemas"]["DonationType"];
            /**
             * Donated On
             * Format: date
             */
            donated_on: string;
            /** Center Name */
            center_name: string | null;
        };
        /** DonationHistory */
        DonationHistory: {
            /** Total */
            total: number;
            /** Years */
            years: components["schemas"]["DonationYear"][];
        };
        /**
         * DonationType
         * @description Вид донации: цельная кровь или плазма.
         * @enum {string}
         */
        DonationType: "whole_blood" | "plasma";
        /** DonationYear */
        DonationYear: {
            /** Year */
            year: number;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["Donation"][];
        };
        /** Eligibility */
        Eligibility: {
            next_allowed: components["schemas"]["NextAllowed"];
            interval_active: components["schemas"]["IntervalActive"];
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Fields */
            fields: {
                [key: string]: string;
            } | null;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "unauthorized" | "not_found" | "validation_error" | "slot_not_found" | "slot_taken" | "active_exists" | "interval_not_passed" | "personal_data_incomplete" | "appointment_not_found" | "appointment_not_active" | "demo_disabled" | "donation_not_found" | "group_not_found" | "group_closed" | "bot_send_failed" | "internal_error";
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** Group */
        Group: {
            /** Code */
            code: string;
            center: components["schemas"]["GroupCenter"];
            /**
             * Date
             * Format: date
             */
            date: string;
            donation_type: components["schemas"]["DonationType"];
            /** Owner Name */
            owner_name: string;
            /** Members */
            members: components["schemas"]["GroupMember"][];
            /** Members Count */
            members_count: number;
            /**
             * Donated Count
             * @description Участники, у которых донация в группе засчитана
             */
            donated_count: number;
            /** Is Member */
            is_member: boolean;
            /** Is Owner */
            is_owner: boolean;
            /**
             * Is Booked
             * @description Текущий пользователь уже записан
             */
            is_booked: boolean;
            /** Is Past */
            is_past: boolean;
            /**
             * Free Slots
             * @description Свободных слотов в центре на дату
             */
            free_slots: number;
            /**
             * Link
             * @description https://max.ru/<бот>?startapp=grp_<code>
             */
            link: string;
            /**
             * Share Text
             * @description Текст для shareMaxContent
             */
            share_text: string;
        };
        /** GroupCenter */
        GroupCenter: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Region Id */
            region_id: number;
        };
        /** GroupCreate */
        GroupCreate: {
            /** Center Id */
            center_id: number;
            /**
             * Date
             * Format: date
             * @description Локальная дата центра
             */
            date: string;
            donation_type: components["schemas"]["DonationType"];
        };
        /** GroupMember */
        GroupMember: {
            /**
             * Name
             * @description Имя и первая буква фамилии: «Иван П.»
             */
            name: string;
            /** Photo Url */
            photo_url: string | null;
            /** Is Owner */
            is_owner: boolean;
            /**
             * Is Booked
             * @description Есть запись в этот центр на эту дату
             */
            is_booked: boolean;
            /**
             * Booked Time
             * @description Время записи участника
             */
            booked_time: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Honorary */
        Honorary: {
            whole: components["schemas"]["HonoraryCounter"];
            plasma: components["schemas"]["HonoraryCounter"];
            mixed: components["schemas"]["HonoraryMixed"];
            /** Achieved */
            achieved: boolean;
            eta: components["schemas"]["HonoraryEta"] | null;
        };
        /** HonoraryCounter */
        HonoraryCounter: {
            /** Count */
            count: number;
            /**
             * Goal
             * @description 40 для крови, 60 для плазмы
             */
            goal: number;
        };
        /** HonoraryEta */
        HonoraryEta: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Years */
            years: number;
            /** Months */
            months: number;
        };
        /** HonoraryMixed */
        HonoraryMixed: {
            /** Count */
            count: number;
            /**
             * Goal
             * @enum {integer}
             */
            goal: 40 | 60;
            /** Whole Needed For 40 */
            whole_needed_for_40: number;
        };
        /**
         * Impact
         * @description «Вклад»: литры и до скольких людей могли помочь донации.
         */
        Impact: {
            /** Whole Count */
            whole_count: number;
            /** Plasma Count */
            plasma_count: number;
            /**
             * Whole Liters
             * @description 0,45 л за донацию цельной крови
             */
            whole_liters: number;
            /**
             * Plasma Liters Max
             * @description До 0,75 л за донацию плазмы
             */
            plasma_liters_max: number;
            /**
             * Total Liters Max
             * @description Верхняя оценка: кровь + плазма
             */
            total_liters_max: number;
            /**
             * Patients Helped Max
             * @description До 3 человек за донацию цельной крови; плазму не считаем
             */
            patients_helped_max: number;
            /** Sources */
            sources: components["schemas"]["ImpactSource"][];
        };
        /** ImpactSource */
        ImpactSource: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Claim */
            claim: string;
        };
        /** IntervalActive */
        IntervalActive: {
            /** Whole Blood */
            whole_blood: boolean;
            /** Plasma */
            plasma: boolean;
        };
        /**
         * LeaveApplicationInput
         * @description Реквизиты для заявления. Не сохраняются. Пустые поля — линии в документе.
         */
        LeaveApplicationInput: {
            /**
             * Employer Name
             * @example ООО «Ромашка»
             */
            employer_name?: string | null;
            /**
             * Head Position
             * @description Должность руководителя в дательном падеже
             * @example Генеральному директору
             */
            head_position?: string | null;
            /**
             * Head Name
             * @description ФИО руководителя в дательном падеже
             * @example Петрову П. П.
             */
            head_name?: string | null;
            /**
             * Employee Position
             * @example менеджер
             */
            employee_position?: string | null;
            /**
             * Rest Date
             * @description Желаемый день отдыха: после дня донации, в течение года
             */
            rest_date?: string | null;
            /**
             * Attach To Vacation
             * @description Присоединить к отпуску вместо rest_date
             * @default false
             */
            attach_to_vacation: boolean;
        };
        /** Level */
        Level: {
            code: components["schemas"]["LevelCode"];
            /** Name */
            name: string;
            /** Threshold */
            threshold: number;
            next: components["schemas"]["NextLevel"] | null;
            /** Is Max */
            is_max: boolean;
        };
        /**
         * LevelCode
         * @description 0 — Будущий донор, 1 — Новичок, 5 — Активный, 10 — Опытный, 20 — Наставник, 40 — Легенда.
         * @enum {string}
         */
        LevelCode: "future_donor" | "novice" | "active" | "experienced" | "mentor" | "legend";
        /** LocateRegionResponse */
        LocateRegionResponse: {
            region: components["schemas"]["Region"] | null;
        };
        /** MapCenter */
        MapCenter: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Region Id */
            region_id: number;
            /** City */
            city: string | null;
            /** Center Type */
            center_type: string | null;
            /** Phone */
            phone: string | null;
            /** Work Hours */
            work_hours: string | null;
            /** Booking Info */
            booking_info: string | null;
            /** Donation Types */
            donation_types: string | null;
            /** Donor Requirements */
            donor_requirements: string | null;
            /** Notes */
            notes: string | null;
            /** Data Status */
            data_status: string | null;
            /** Source Url */
            source_url: string | null;
            /** Source Url 2 */
            source_url_2: string | null;
            /** Verified On */
            verified_on: string | null;
            /** Statuses */
            statuses: {
                [key: string]: components["schemas"]["StockStatus"];
            };
            worst: components["schemas"]["StockStatus"] | null;
        };
        /** MapRegion */
        MapRegion: {
            /** Code */
            code: string;
            /** Statuses */
            statuses: {
                [key: string]: components["schemas"]["StockStatus"];
            };
            worst: components["schemas"]["StockStatus"] | null;
        };
        /** MapStatus */
        MapStatus: {
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Regions */
            regions: components["schemas"]["MapRegion"][];
        };
        /** Me */
        Me: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string | null;
            /** Photo Url */
            photo_url: string | null;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            blood: components["schemas"]["BloodInfo"];
            /** Referrals Count */
            referrals_count: number;
            /** @description Регион донора для пушей о дефиците */
            region?: components["schemas"]["RegionShort"] | null;
        };
        /** NextAllowed */
        NextAllowed: {
            /**
             * Whole Blood
             * Format: date
             */
            whole_blood: string;
            /**
             * Plasma
             * Format: date
             */
            plasma: string;
        };
        /** NextLevel */
        NextLevel: {
            code: components["schemas"]["LevelCode"];
            /** Name */
            name: string;
            /** Threshold */
            threshold: number;
            /** Remaining */
            remaining: number;
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /**
             * Consent
             * @constant
             */
            consent: true;
        };
        /** PersonalData */
        PersonalData: {
            /** Last Name */
            last_name: string | null;
            /** First Name */
            first_name: string | null;
            /** Middle Name */
            middle_name: string | null;
            /** Passport Series */
            passport_series: string | null;
            /** Passport Number */
            passport_number: string | null;
            /** Passport Issued By */
            passport_issued_by: string | null;
            /** Passport Division Code */
            passport_division_code: string | null;
            /** Oms Number */
            oms_number: string | null;
            /** Phone */
            phone: string | null;
            /** Email */
            email: string | null;
            /** Is Demo */
            is_demo: boolean;
            /** Missing Fields */
            missing_fields: components["schemas"]["PersonalDataField"][];
        };
        /**
         * PersonalDataField
         * @enum {string}
         */
        PersonalDataField: "last_name" | "first_name" | "middle_name" | "passport_series" | "passport_number" | "passport_issued_by" | "passport_division_code" | "oms_number" | "phone" | "email";
        /**
         * PersonalDataInput
         * @description Сохраняется по разделам настроек: поля, которых нет в теле, не меняются.
         */
        PersonalDataInput: {
            /** Last Name */
            last_name?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Middle Name */
            middle_name?: string | null;
            /** Passport Series */
            passport_series?: string | null;
            /** Passport Number */
            passport_number?: string | null;
            /** Passport Issued By */
            passport_issued_by?: string | null;
            /** Passport Division Code */
            passport_division_code?: string | null;
            /** Oms Number */
            oms_number?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
        };
        /** Progress */
        Progress: {
            /** Total */
            total: number;
            level: components["schemas"]["Level"];
            honorary: components["schemas"]["Honorary"];
        };
        /** Referrals */
        Referrals: {
            /** Count */
            count: number;
            /** Link */
            link: string;
        };
        /** Region */
        Region: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Has Centers */
            has_centers: boolean;
        };
        /** RegionShort */
        RegionShort: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** RegionUpdate */
        RegionUpdate: {
            /** Region Id */
            region_id: number;
        };
        /** RestDay */
        RestDay: {
            /**
             * Deadline
             * Format: date
             * @description До какой даты можно взять день отдыха
             */
            deadline: string;
            /**
             * Days Left
             * @description Дней до deadline, < 0 — срок прошёл
             */
            days_left: number;
            /** Used */
            used: boolean;
            /** Used At */
            used_at: string | null;
        };
        /** RestDayUpdate */
        RestDayUpdate: {
            /** Used */
            used: boolean;
        };
        /**
         * ShareCard
         * @description Данные карточки «Я сдал кровь» / «Мой уровень» и текст для shareMaxContent.
         */
        ShareCard: {
            kind: components["schemas"]["ShareCardKind"];
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Total */
            total: number;
            level: components["schemas"]["Level"];
            /** Patients Helped Max */
            patients_helped_max: number;
            /** Last Donation On */
            last_donation_on: string | null;
            /**
             * Text
             * @description text для shareMaxContent
             */
            text: string;
            /**
             * Link
             * @description link для shareMaxContent — реферальная ссылка
             */
            link: string;
        };
        /**
         * ShareCardKind
         * @enum {string}
         */
        ShareCardKind: "donation" | "level";
        /** Slot */
        Slot: {
            /** Id */
            id: number;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Local Time
             * @example 09:30
             */
            local_time: string;
            /** Is Free */
            is_free: boolean;
        };
        /** SlotGroup */
        SlotGroup: {
            period: components["schemas"]["SlotPeriod"];
            /** Slots */
            slots: components["schemas"]["Slot"][];
        };
        /**
         * SlotPeriod
         * @enum {string}
         */
        SlotPeriod: "morning" | "day" | "evening";
        /** SlotRequest */
        SlotRequest: {
            /** Slot Id */
            slot_id: number;
        };
        /** SlotsCenter */
        SlotsCenter: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address: string;
        };
        /**
         * StockStatus
         * @description Запас крови группы: нет строки в таблице — «нет данных».
         * @enum {string}
         */
        StockStatus: "urgent" | "low" | "enough";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_onboarding: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_personal_data: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalData"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_personal_data: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalDataInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalData"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_eligibility: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eligibility"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_donations: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonationHistory"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_referrals: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Referrals"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_region: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_impact: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Impact"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_card: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ShareCardKind"];
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareCard"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_after_donation: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfterDonationResponse"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_donation_after: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                donation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfterDonation"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rest_day: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                donation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestDayUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AfterDonation"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_leave_application: {
        parameters: {
            query?: {
                format?: components["schemas"]["DocFormat"];
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                donation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveApplicationInput"];
            };
        };
        responses: {
            /** @description Файл заявления */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    send_leave_application: {
        parameters: {
            query?: {
                format?: components["schemas"]["DocFormat"];
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                donation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveApplicationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Бот не смог отправить сообщение */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_regions: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"][];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locate_region: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocateRegionResponse"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_map_status: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapStatus"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_map_centers: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapCenter"][];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_dates: {
        parameters: {
            query: {
                region_id: number;
                donation_type: components["schemas"]["DonationType"];
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDates"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_booking_centers: {
        parameters: {
            query: {
                region_id: number;
                donation_type: components["schemas"]["DonationType"];
                date: string;
                lat?: number | null;
                lon?: number | null;
                pin_center_id?: number | null;
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingCenter"][];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_booking_slots: {
        parameters: {
            query: {
                center_id: number;
                donation_type: components["schemas"]["DonationType"];
                date: string;
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingSlots"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_current_appointment: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_appointment: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reschedule_appointment: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_appointment: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Ошибка валидации */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    my_groups: {
        parameters: {
            query?: {
                past?: boolean;
            };
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_group: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_group: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_reset: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_remind: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_complete: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_ask_donated: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_push: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path: {
                kind: components["schemas"]["DemoPushKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_run_daily: {
        parameters: {
            query?: never;
            header?: {
                "x-max-init-data"?: string | null;
                "x-dev-user-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyRunResult"];
                };
            };
            /** @description Нет или невалидна initData */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
