/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущий пользователь
         * @description При первом запросе бэк создаёт пользователя и демо-профиль (§5.4),
         *     обрабатывает `start_param = ref_<code>`.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить онбординг и дать согласие на обработку ПД */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/personal-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Личные данные */
        get: operations["getPersonalData"];
        /**
         * Сохранить личные данные
         * @description Значения передаются без маски. Ошибки валидации — 422 с `fields`,
         *     тексты из `confirming.md`:
         *
         *     | Поле | Текст ошибки |
         *     |------|--------------|
         *     | last_name | Введите фамилию |
         *     | first_name | Введите имя |
         *     | passport_series | Серия — 4 цифры |
         *     | passport_number | Номер — 6 цифр |
         *     | passport_issued_by | Укажите, кем выдан паспорт |
         *     | passport_division_code | Код подразделения — 6 цифр |
         *     | oms_number | Номер полиса — 16 цифр |
         *     | phone | Введите номер телефона полностью |
         *     | email | Проверьте адрес почты |
         */
        put: operations["updatePersonalData"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ближайшие разрешённые даты донации (§5.1) */
        get: operations["getEligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Уровень донора и путь к званию «Почётный донор России» (§5.2, §5.3) */
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/donations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История донаций, по годам от новых к старым */
        get: operations["getDonations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Рефералы */
        get: operations["getReferrals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все субъекты РФ по алфавиту */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Регион по координатам */
        get: operations["locateRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карта-светофор по регионам */
        get: operations["getMapStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Календарь доступности на 2 месяца
         * @description День доступен, если в регионе есть свободный слот этого вида и день ≥ `earliest_allowed`.
         *     `days` покрывает весь диапазон `from`..`to` включительно.
         */
        get: operations["getBookingDates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking/centers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Центры со свободными слотами на дату
         * @description Только центры со свободными слотами. Сортировка: сначала `urgent` для группы
         *     пользователя, дальше по расстоянию, без геопозиции — по алфавиту.
         *     `pin_center_id` (при переносе) ставит этот центр первым.
         */
        get: operations["getBookingCenters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Слоты центра на дату, сгруппированные по времени суток
         * @description Шаг 15 минут. Утро — до 12:00, день — 12:00–17:00, вечер — после 17:00
         *     по местному времени региона. Пустые группы не отдаются.
         */
        get: operations["getBookingSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активная запись пользователя */
        get: operations["getCurrentAppointment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Записаться
         * @description После записи бот отправляет подтверждение в чат (ошибка отправки запись не отменяет).
         */
        post: operations["createAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Перенести запись на другой слот
         * @description В одной транзакции: старая запись → `rescheduled`, новая → `active`.
         *     Возвращается новая запись (у неё другой `id`).
         */
        post: operations["rescheduleAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить запись */
        post: operations["cancelAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вернуть профиль к демо-состоянию и отменить записи */
        post: operations["demoReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/appointments/{id}/remind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить напоминание по записи сразу */
        post: operations["demoRemind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/appointments/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Засчитать донацию по записи
         * @description Запись → `completed`, в историю добавляется донация.
         */
        post: operations["demoComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Текст для логов/отладки. Пользователю показываем тексты из md по `code` */
                message: string;
                /** @description Только для 422 при сохранении формы. Ключ — имя поля, значение — текст ошибки */
                fields: {
                    [key: string]: string;
                } | null;
            };
        };
        /** @enum {string} */
        ErrorCode: "unauthorized" | "not_found" | "validation_error" | "slot_not_found" | "slot_taken" | "active_exists" | "interval_not_passed" | "personal_data_incomplete" | "appointment_not_found" | "appointment_not_active" | "demo_disabled" | "internal_error";
        /** @enum {string} */
        DonationType: "whole_blood" | "plasma";
        /**
         * @description 1 = O(I), 2 = A(II), 3 = B(III), 4 = AB(IV); знак — резус
         * @enum {string}
         */
        BloodGroup: "1+" | "1-" | "2+" | "2-" | "3+" | "3-" | "4+" | "4-";
        /** @enum {string} */
        StockStatus: "urgent" | "low" | "enough";
        /** @example 09:30 */
        LocalTime: string;
        Me: {
            id: number;
            first_name: string;
            last_name: string | null;
            /** Format: uri */
            photo_url: string | null;
            onboarding_completed: boolean;
            blood: components["schemas"]["BloodInfo"];
            referrals_count: number;
        };
        /** @description `null` в любом поле — значение неизвестно («—» на экране) */
        BloodInfo: {
            group: components["schemas"]["BloodGroup"] | null;
            /** @enum {string|null} */
            kell: "K+" | "K-" | null;
            /** @example CcDee */
            phenotype: string | null;
            donor_code: string | null;
        };
        OnboardingRequest: {
            /** @constant */
            consent: true;
        };
        /** @enum {string} */
        PersonalDataFieldName: "last_name" | "first_name" | "middle_name" | "passport_series" | "passport_number" | "passport_issued_by" | "passport_division_code" | "oms_number" | "phone" | "email";
        /** @description `null` — поле не заполнено (на экране «Не указано» красным для обязательных) */
        PersonalData: {
            last_name: string | null;
            first_name: string | null;
            middle_name: string | null;
            passport_series: string | null;
            passport_number: string | null;
            passport_issued_by: string | null;
            passport_division_code: string | null;
            oms_number: string | null;
            phone: string | null;
            /** Format: email */
            email: string | null;
            is_demo: boolean;
            /** @description Незаполненные обязательные поля. Пустой — можно нажимать «Далее» */
            missing_fields: components["schemas"]["PersonalDataFieldName"][];
        };
        /** @description Значения без маски */
        PersonalDataInput: {
            last_name: string;
            first_name: string;
            middle_name?: string | null;
            passport_series: string;
            passport_number: string;
            passport_issued_by: string;
            passport_division_code: string;
            oms_number: string;
            phone: string;
            /** Format: email */
            email: string;
        };
        Eligibility: {
            /** @description Ближайшая дата, с которой можно сдать (≥ сегодня) */
            next_allowed: {
                /** Format: date */
                whole_blood: string;
                /** Format: date */
                plasma: string;
            };
            /** @description `false` — интервал прошёл, подпись «можно сдать с …» не показываем */
            interval_active: {
                whole_blood: boolean;
                plasma: boolean;
            };
        };
        /**
         * @description future_donor (0) — Будущий донор, novice (1) — Новичок, active (5) — Активный донор,
         *     experienced (10) — Опытный донор, mentor (20) — Наставник, legend (40) — Легенда донорства
         * @enum {string}
         */
        LevelCode: "future_donor" | "novice" | "active" | "experienced" | "mentor" | "legend";
        Progress: {
            /** @description Всего донаций (кровь + плазма) */
            total: number;
            level: {
                code: components["schemas"]["LevelCode"];
                name: string;
                threshold: number;
                /** @description `null` на последнем уровне */
                next: {
                    code: components["schemas"]["LevelCode"];
                    name: string;
                    threshold: number;
                    remaining: number;
                } | null;
                is_max: boolean;
            };
            honorary: {
                whole: components["schemas"]["HonoraryCounter"];
                plasma: components["schemas"]["HonoraryCounter"];
                mixed: {
                    /** @description X + Y */
                    count: number;
                    /**
                     * @description 40, если цельной крови ≥ 25, иначе 60
                     * @enum {integer}
                     */
                    goal: 40 | 60;
                    /** @description 25 − X, 0 если X ≥ 25. Подсказка «Ещё N сдач цельной крови — и цель сократится до 40» — при goal = 60 */
                    whole_needed_for_40: number;
                };
                /** @description Донаций для звания достаточно */
                achieved: boolean;
                /** @description Срок до звания по самому быстрому пути. `null`, если achieved */
                eta: {
                    /** Format: date */
                    date: string;
                    years: number;
                    months: number;
                } | null;
            };
        };
        HonoraryCounter: {
            count: number;
            /** @description 40 для крови, 60 для плазмы */
            goal: number;
        };
        DonationHistory: {
            total: number;
            /** @description От нового года к старому. Пустой — «Здесь появятся ваши донации» */
            years: {
                year: number;
                count: number;
                /** @description От новой к старой */
                items: components["schemas"]["Donation"][];
            }[];
        };
        Donation: {
            id: number;
            donation_type: components["schemas"]["DonationType"];
            /** Format: date */
            donated_on: string;
            center_name: string | null;
        };
        Referrals: {
            count: number;
            /**
             * Format: uri
             * @description https://max.ru/<bot>?startapp=ref_<code>
             */
            link: string;
        };
        Region: {
            id: number;
            /** @description ISO 3166-2, например RU-MOW. Совпадает с `code` в topojson */
            code: string;
            name: string;
            /** @description `false` — строка серая, «Нет центров для записи» */
            has_centers: boolean;
        };
        LocateRegionResponse: {
            region: components["schemas"]["Region"] | null;
        };
        /** @description Статус по группе. Нет ключа — нет данных по этой группе */
        BloodStatuses: {
            "1+"?: components["schemas"]["StockStatus"];
            "1-"?: components["schemas"]["StockStatus"];
            "2+"?: components["schemas"]["StockStatus"];
            "2-"?: components["schemas"]["StockStatus"];
            "3+"?: components["schemas"]["StockStatus"];
            "3-"?: components["schemas"]["StockStatus"];
            "4+"?: components["schemas"]["StockStatus"];
            "4-"?: components["schemas"]["StockStatus"];
        };
        MapStatus: {
            /** Format: date-time */
            updated_at: string;
            /** @description Все регионы. Регион без данных — `statuses = {}`, `worst = null` */
            regions: {
                code: string;
                statuses: components["schemas"]["BloodStatuses"];
                /** @description Худший статус среди всех групп, `null` — нет данных */
                worst: components["schemas"]["StockStatus"] | null;
            }[];
        };
        BookingDates: {
            /**
             * Format: date
             * @description Сегодня
             */
            from: string;
            /**
             * Format: date
             * @description Сегодня + 2 месяца
             */
            to: string;
            /**
             * Format: date
             * @description `next_allowed` для выбранного вида. Если > from — показываем подпись про интервал
             */
            earliest_allowed: string;
            /** @description Первая доступная дата (открываем календарь на её месяце). `null` — мест нет в ближайшие 2 месяца */
            first_available: string | null;
            days: {
                /** Format: date */
                date: string;
                available: boolean;
            }[];
        };
        BookingCenter: {
            id: number;
            name: string;
            address: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            /** Format: uri */
            photo_url: string | null;
            /** @description Свободных мест на выбранную дату */
            free_slots: number;
            /** @description `null`, если lat/lon не переданы */
            distance_km: number | null;
            /** @description Статус группы пользователя в центре. `null` — группа неизвестна или нет данных (строки светофора нет) */
            group_status: components["schemas"]["StockStatus"] | null;
        };
        /**
         * @description morning — до 12:00, day — 12:00–17:00, evening — после 17:00
         * @enum {string}
         */
        SlotPeriod: "morning" | "day" | "evening";
        BookingSlots: {
            center: {
                id: number;
                name: string;
                address: string;
            };
            /** Format: date */
            date: string;
            /** @description В порядке morning → day → evening, пустые группы не отдаются */
            groups: {
                period: components["schemas"]["SlotPeriod"];
                slots: components["schemas"]["Slot"][];
            }[];
        };
        Slot: {
            id: number;
            /** Format: date-time */
            starts_at: string;
            local_time: components["schemas"]["LocalTime"];
            is_free: boolean;
        };
        SlotRequest: {
            slot_id: number;
        };
        Appointment: {
            id: number;
            donation_type: components["schemas"]["DonationType"];
            /** Format: date-time */
            starts_at: string;
            /**
             * Format: date
             * @description Дата по местному времени региона центра
             */
            local_date: string;
            local_time: components["schemas"]["LocalTime"];
            center: {
                id: number;
                name: string;
                address: string;
                region_id: number;
            };
        };
        /** @description Общий ответ для current / create / reschedule / cancel — можно сразу класть в кэш `/appointments/current` */
        AppointmentResponse: {
            appointment: components["schemas"]["Appointment"] | null;
        };
    };
    responses: {
        /** @description Нет или невалидна initData */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "Не удалось проверить пользователя",
                 *         "fields": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Регион или центр не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "not_found",
                 *         "message": "Не найдено",
                 *         "fields": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Неверные параметры запроса */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "validation_error",
                 *         "message": "Неверные параметры запроса",
                 *         "fields": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Слот не найден */
        SlotNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "slot_not_found",
                 *         "message": "Слот не найден",
                 *         "fields": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Запись не найдена или принадлежит другому пользователю */
        AppointmentNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "appointment_not_found",
                 *         "message": "Запись не найдена",
                 *         "fields": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `slot_not_found` или `appointment_not_found` */
        SlotOrAppointmentNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Запись уже отменена, перенесена или завершена */
        AppointmentNotActive: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "appointment_not_active",
                 *         "message": "Запись уже неактивна",
                 *         "fields": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description - `slot_taken` — слот заняли (окно «Это время уже заняли»);
         *     - `active_exists` — у пользователя уже есть активная запись.
         */
        BookingConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description - `interval_not_passed` — дата слота раньше `next_allowed` для этого вида;
         *     - `personal_data_incomplete` — не заполнены обязательные личные данные.
         */
        BookingUnprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description DEMO_MODE выключен */
        DemoDisabled: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "demo_disabled",
                 *         "message": "Демо-режим выключен",
                 *         "fields": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `demo_disabled` или `appointment_not_found` */
        DemoOrAppointmentNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        RegionIdQuery: number;
        DonationTypeQuery: components["schemas"]["DonationType"];
        DateQuery: string;
        AppointmentIdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "first_name": "Иван",
                     *       "last_name": "Иванов",
                     *       "photo_url": null,
                     *       "onboarding_completed": false,
                     *       "blood": {
                     *         "group": "2+",
                     *         "kell": "K-",
                     *         "phenotype": "CcDee",
                     *         "donor_code": "1234-5678"
                     *       },
                     *       "referrals_count": 3
                     *     }
                     */
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Онбординг завершён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getPersonalData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "last_name": "Иванов",
                     *       "first_name": "Иван",
                     *       "middle_name": "Иванович",
                     *       "passport_series": "4510",
                     *       "passport_number": "123456",
                     *       "passport_issued_by": "ГУ МВД России по г. Москве",
                     *       "passport_division_code": "770-001",
                     *       "oms_number": "1234567890123456",
                     *       "phone": "+79001234567",
                     *       "email": "ivanov@mail.ru",
                     *       "is_demo": true,
                     *       "missing_fields": []
                     *     }
                     */
                    "application/json": components["schemas"]["PersonalData"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updatePersonalData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalDataInput"];
            };
        };
        responses: {
            /** @description Сохранено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalData"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Ошибки в форме */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_error",
                     *         "message": "Проверьте данные",
                     *         "fields": {
                     *           "passport_series": "Серия — 4 цифры",
                     *           "phone": "Введите номер телефона полностью"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEligibility: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "next_allowed": {
                     *         "whole_blood": "2026-10-12",
                     *         "plasma": "2026-09-26"
                     *       },
                     *       "interval_active": {
                     *         "whole_blood": true,
                     *         "plasma": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Eligibility"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "total": 12,
                     *       "level": {
                     *         "code": "experienced",
                     *         "name": "Опытный донор",
                     *         "threshold": 10,
                     *         "next": {
                     *           "code": "mentor",
                     *           "name": "Наставник",
                     *           "threshold": 20,
                     *           "remaining": 8
                     *         },
                     *         "is_max": false
                     *       },
                     *       "honorary": {
                     *         "whole": {
                     *           "count": 10,
                     *           "goal": 40
                     *         },
                     *         "plasma": {
                     *           "count": 2,
                     *           "goal": 60
                     *         },
                     *         "mixed": {
                     *           "count": 12,
                     *           "goal": 60,
                     *           "whole_needed_for_40": 15
                     *         },
                     *         "achieved": false,
                     *         "eta": {
                     *           "date": "2032-04-14",
                     *           "years": 5,
                     *           "months": 6
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Progress"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDonations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "total": 12,
                     *       "years": [
                     *         {
                     *           "year": 2026,
                     *           "count": 2,
                     *           "items": [
                     *             {
                     *               "id": 12,
                     *               "donation_type": "whole_blood",
                     *               "donated_on": "2026-08-12",
                     *               "center_name": "Центр крови ФМБА России"
                     *             },
                     *             {
                     *               "id": 11,
                     *               "donation_type": "plasma",
                     *               "donated_on": "2026-06-02",
                     *               "center_name": "ГКБ им. С. П. Боткина"
                     *             }
                     *           ]
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["DonationHistory"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getReferrals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "count": 3,
                     *       "link": "https://max.ru/kaplya_bot?startapp=ref_aB3dE9"
                     *     }
                     */
                    "application/json": components["schemas"]["Referrals"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 1,
                     *         "code": "RU-AD",
                     *         "name": "Адыгея",
                     *         "has_centers": true
                     *       },
                     *       {
                     *         "id": 77,
                     *         "code": "RU-MOW",
                     *         "name": "Москва",
                     *         "has_centers": true
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Region"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    locateRegion: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. `region = null`, если точка вне РФ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "region": {
                     *         "id": 77,
                     *         "code": "RU-MOW",
                     *         "name": "Москва",
                     *         "has_centers": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["LocateRegionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMapStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "updated_at": "2026-09-24T09:00:00+03:00",
                     *       "regions": [
                     *         {
                     *           "code": "RU-MOW",
                     *           "statuses": {
                     *             "1+": "urgent",
                     *             "1-": "low",
                     *             "2+": "enough",
                     *             "2-": "low",
                     *             "3+": "enough",
                     *             "3-": "urgent",
                     *             "4+": "enough",
                     *             "4-": "low"
                     *           },
                     *           "worst": "urgent"
                     *         },
                     *         {
                     *           "code": "RU-CHU",
                     *           "statuses": {},
                     *           "worst": null
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["MapStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBookingDates: {
        parameters: {
            query: {
                region_id: components["parameters"]["RegionIdQuery"];
                donation_type: components["parameters"]["DonationTypeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "from": "2026-09-26",
                     *       "to": "2026-11-26",
                     *       "earliest_allowed": "2026-10-12",
                     *       "first_available": "2026-10-13",
                     *       "days": [
                     *         {
                     *           "date": "2026-09-26",
                     *           "available": false
                     *         },
                     *         {
                     *           "date": "2026-10-13",
                     *           "available": true
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["BookingDates"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getBookingCenters: {
        parameters: {
            query: {
                region_id: components["parameters"]["RegionIdQuery"];
                donation_type: components["parameters"]["DonationTypeQuery"];
                date: components["parameters"]["DateQuery"];
                /** @description Передаётся вместе с lon */
                lat?: number;
                /** @description Передаётся вместе с lat */
                lon?: number;
                pin_center_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. Пустой массив — «На эту дату мест нет» */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 5,
                     *         "name": "Центр крови ФМБА России",
                     *         "address": "ул. Поликарпова, 14",
                     *         "lat": 55.7766,
                     *         "lon": 37.5305,
                     *         "photo_url": null,
                     *         "free_slots": 12,
                     *         "distance_km": 2.3,
                     *         "group_status": "urgent"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["BookingCenter"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getBookingSlots: {
        parameters: {
            query: {
                center_id: number;
                donation_type: components["parameters"]["DonationTypeQuery"];
                date: components["parameters"]["DateQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. Все `is_free = false` — «На этот день всё занято» */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "center": {
                     *         "id": 5,
                     *         "name": "Центр крови ФМБА России",
                     *         "address": "ул. Поликарпова, 14"
                     *       },
                     *       "date": "2026-10-14",
                     *       "groups": [
                     *         {
                     *           "period": "morning",
                     *           "slots": [
                     *             {
                     *               "id": 1001,
                     *               "starts_at": "2026-10-14T08:00:00+03:00",
                     *               "local_time": "08:00",
                     *               "is_free": false
                     *             },
                     *             {
                     *               "id": 1002,
                     *               "starts_at": "2026-10-14T08:15:00+03:00",
                     *               "local_time": "08:15",
                     *               "is_free": true
                     *             }
                     *           ]
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["BookingSlots"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getCurrentAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotRequest"];
            };
        };
        responses: {
            /** @description Запись создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["SlotNotFound"];
            409: components["responses"]["BookingConflict"];
            422: components["responses"]["BookingUnprocessable"];
        };
    };
    rescheduleAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotRequest"];
            };
        };
        responses: {
            /** @description Запись перенесена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["SlotOrAppointmentNotFound"];
            409: components["responses"]["BookingConflict"];
            422: components["responses"]["BookingUnprocessable"];
        };
    };
    cancelAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Запись отменена, активной записи больше нет */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "appointment": null
                     *     }
                     */
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["AppointmentNotFound"];
            409: components["responses"]["AppointmentNotActive"];
        };
    };
    demoReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DemoDisabled"];
        };
    };
    demoRemind: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Напоминание отправлено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DemoOrAppointmentNotFound"];
        };
    };
    demoComplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Донация засчитана */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["DemoOrAppointmentNotFound"];
            409: components["responses"]["AppointmentNotActive"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
}
