"""initial schema

Revision ID: 678d5805b4e0
Revises:
Create Date: 2026-09-26 14:10:09.856609

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "678d5805b4e0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("max_user_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("photo_url", sa.String(length=2048), nullable=True),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "blood_group",
            sa.Enum("1+", "1-", "2+", "2-", "3+", "3-", "4+", "4-", name="blood_group"),
            nullable=True,
        ),
        sa.Column("kell", sa.String(length=2), nullable=True),
        sa.Column("phenotype", sa.String(length=16), nullable=True),
        sa.Column("donor_code", sa.String(length=9), nullable=True),
        sa.Column("referral_code", sa.String(length=32), nullable=False),
        sa.Column("referred_by_user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referred_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("max_user_id"),
        sa.UniqueConstraint("referral_code"),
    )
    op.create_index(
        op.f("ix_users_referred_by_user_id"),
        "users",
        ["referred_by_user_id"],
        unique=False,
    )
    op.create_table(
        "centers",
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=False),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("photo_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_centers_region_id"), "centers", ["region_id"], unique=False
    )
    op.create_table(
        "donations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "donation_type",
            sa.Enum("whole_blood", "plasma", name="donation_type"),
            nullable=False,
        ),
        sa.Column("donated_on", sa.Date(), nullable=False),
        sa.Column("center_name", sa.String(length=255), nullable=True),
        sa.Column(
            "is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_donations_user_id"), "donations", ["user_id"], unique=False
    )
    op.create_table(
        "personal_data",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("middle_name", sa.String(length=255), nullable=True),
        sa.Column("passport_series", sa.String(length=4), nullable=True),
        sa.Column("passport_number", sa.String(length=6), nullable=True),
        sa.Column("passport_issued_by", sa.String(length=512), nullable=True),
        sa.Column("passport_division_code", sa.String(length=7), nullable=True),
        sa.Column("oms_number", sa.String(length=16), nullable=True),
        sa.Column("phone", sa.String(length=12), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column(
            "is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "region_blood_status",
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column(
            "blood_group",
            sa.Enum("1+", "1-", "2+", "2-", "3+", "3-", "4+", "4-", name="blood_group"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("urgent", "low", "enough", name="stock_status"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("region_id", "blood_group"),
    )
    op.create_table(
        "center_blood_status",
        sa.Column("center_id", sa.Integer(), nullable=False),
        sa.Column(
            "blood_group",
            sa.Enum("1+", "1-", "2+", "2-", "3+", "3-", "4+", "4-", name="blood_group"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("urgent", "low", "enough", name="stock_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["center_id"], ["centers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("center_id", "blood_group"),
    )
    op.create_table(
        "slots",
        sa.Column("center_id", sa.Integer(), nullable=False),
        sa.Column(
            "donation_type",
            sa.Enum("whole_blood", "plasma", name="donation_type"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "is_blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["center_id"], ["centers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "center_id",
            "donation_type",
            "starts_at",
            name="uq_slots_center_type_starts_at",
        ),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column("center_id", sa.Integer(), nullable=False),
        sa.Column(
            "donation_type",
            sa.Enum("whole_blood", "plasma", name="donation_type"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "cancelled",
                "rescheduled",
                "completed",
                name="appointment_status",
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("rescheduled_from_id", sa.Integer(), nullable=True),
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["center_id"],
            ["centers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rescheduled_from_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["slots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointments_slot_id"), "appointments", ["slot_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_starts_at"), "appointments", ["starts_at"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_status"), "appointments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_user_id"), "appointments", ["user_id"], unique=False
    )
    op.create_index(
        "uq_active_slot",
        "appointments",
        ["slot_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "uq_active_user",
        "appointments",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_user",
        table_name="appointments",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "uq_active_slot",
        table_name="appointments",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_appointments_user_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_starts_at"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_slot_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_table("slots")
    op.drop_table("center_blood_status")
    op.drop_table("region_blood_status")
    op.drop_table("personal_data")
    op.drop_index(op.f("ix_donations_user_id"), table_name="donations")
    op.drop_table("donations")
    op.drop_index(op.f("ix_centers_region_id"), table_name="centers")
    op.drop_table("centers")
    op.drop_index(op.f("ix_users_referred_by_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("regions")
    # ### end Alembic commands ###

    # alembic не удаляет enum-типы вместе с таблицами
    for type_name in (
        "appointment_status",
        "stock_status",
        "donation_type",
        "blood_group",
    ):
        sa.Enum(name=type_name).drop(op.get_bind(), checkfirst=True)
